config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :content_items, only: %i[index show new create edit update destroy] do
    collection do
      get 'calendar'
    end
  end
  resources :social_networks, only: %i[index new create]

  root to: 'content_items#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content_item.rb
# frozen_string_literal: true

class ContentItem < ApplicationRecord
  belongs_to :user
  has_many :publishing_targets, dependent: :destroy
  has_many :social_networks, through: :publishing_targets

  accepts_nested_attributes_for :publishing_targets, allow_destroy: true,
                                                     reject_if: proc { |attributes|
                                                                  attributes['social_network_id'].blank? || attributes['publishing_date'].blank?
                                                                }

  has_rich_text :body
end

app/models/publishing_target.rb
# frozen_string_literal: true

class PublishingTarget < ApplicationRecord
  belongs_to :content_item
  belongs_to :social_network

  def start_time
    publishing_date
  end
end

app/models/social_network.rb
# frozen_string_literal: true

class SocialNetwork < ApplicationRecord
  belongs_to :user
  has_many :publishing_targets, dependent: :destroy
  has_many :content_items, through: :publishing_targets
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :content_items, dependent: :destroy
  has_many :social_networks, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/content_items_controller.rb
# frozen_string_literal: true

class ContentItemsController < SecureController
  def index
    @content_items = current_user.content_items
  end

  def show
    @content_item = ContentItem.find(params[:id])
  end

  def new
    @content_item = ContentItem.new
    @content_item.user = current_user
    @content_item.publishing_targets.build
  end

  def create
    @content_item = ContentItem.new(content_item_params)
    @content_item.user = current_user

    if @content_item.save
      redirect_to content_items_path, notice: "#{@content_item.title} added"
    else
      render :new
    end
  end

  def edit
    @content_item = ContentItem.find(params[:id])
    @content_item.publishing_targets.build
  end

  def update
    @content_item = ContentItem.find(params[:id])
    @content_item.assign_attributes(content_item_params)

    if @content_item.save
      redirect_to content_items_path, notice: "#{@content_item.title} updated"
    else
      render :edit
    end
  end

  def destroy
    @content_item = current_user.content_items.find(params[:id])
    @content_item.destroy

    redirect_to content_items_path, notice: "#{@content_item.title} deleted"
  end

  def calendar
    @search = ContentItemsSearch.new(params[:search], current_user)
    @publishing_targets = @search.results
  end

  private

  def content_item_params
    params.require(:content_item).permit(:title, :body, publishing_targets_attributes: %i[social_network_id publishing_date])
  end
end

app/controllers/secure_controller.rb
# frozen_string_literal: true

class SecureController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/social_networks_controller.rb
# frozen_string_literal: true

class SocialNetworksController < SecureController
  def index; end

  def new
    @social_network = SocialNetwork.new
  end

  def create
    @social_network = SocialNetwork.new(social_network_params)
    @social_network.user = current_user

    if @social_network.save
      redirect_to social_networks_path, notice: "#{@social_network.description} added"
    else
      render :new
    end
  end

  private

  def social_network_params
    params.require(:social_network).permit(:description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_main_navigation.html.erb
<ul>
  <li><%= link_to 'Content Items', content_items_path %></li>
  <li><%= link_to 'Social Networks', social_networks_path %></li>
  <li><%= link_to 'Calender', calendar_content_items_path %></li>
</ul>

app/views/content_items/_content_item.html.erb
<li>
  <div><%= link_to content_item.title, content_item %></div>
</li>

app/views/content_items/_content_item_filters.html.erb
<%= simple_form_for :search, method: :get do |f| %>
  <div class="row mb-2">
    <div class="col col-md-4">
      <%= f.input :search_query, input_html: {class: "form-control"}, required: false ,label: "Search"  %>
    </div>
    <div class="col col-md-4">
      <%= f.input :social_network, as: :select, collection: @search.social_networks_options, required: false, label: "Network",input_html: {class: 'form-control chosen-select', multiple: false}, :include_blank => ""%>
    </div>
  </div>
  <div class="row pull-right">
    <div class="col">
      <%= f.button :submit, "Go", class: "btn btn-success" %>
      <%= link_to "Clear", calendar_content_items_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>
<br>
<br>

app/views/content_items/_form.html.erb
<%= form_with model: content_item do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>
  <hr>
  <ul>
    <% content_item.user.social_networks.each_with_index do |network, index| %>
      <li>
        <%= label_tag do %>
          <%= check_box_tag "content_item[publishing_targets_attributes][#{index}][social_network_id]", network.id, content_item.social_network_ids.include?(network.id) %>
          <%= network.description %>
        <% end %>
        <%= label_tag do %>
          Date
          <%= datetime_field_tag "content_item[publishing_targets_attributes][#{index}][publishing_date]" %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/content_items/calendar.html.erb
<h1>Content Items</h1>

<%= render partial: 'content_item_filters' %>

<%= month_calendar(events: @publishing_targets) do |date, publishing_targets| %>
  <p><%=date.day %></p>
  <% publishing_targets.each do |publishing_target|%>
      <% content_item = publishing_target.content_item%>
      <% social_network = publishing_target.social_network%>
      <p><%= link_to "#{content_item.title} || Network: #{social_network.description}" , content_item %></p>
  <% end %>
<% end %>

app/views/content_items/edit.html.erb
<h1>Edit <%= @content_item.title %></h1>

<%= render 'form', content_item: @content_item %>

app/views/content_items/index.html.erb
<h1>Content Items</h1>

<%= link_to 'Add Content item', new_content_item_path %>

<ul id="content-items">
  <%= render partial: 'content_item', collection: @content_items %>
</ul>

app/views/content_items/new.html.erb
<h1>New Content Item</h1>

<%= render 'form', content_item: @content_item %>

app/views/content_items/show.html.erb
<h1><%= @content_item.title %></h1>

<div><%= link_to 'Edit', edit_content_item_path(@content_item) %></div>
<div><%= link_to 'Delete', content_item_path(@content_item), method: :delete, 'data-confirm': 'Are you sure?' %></div>

<hr>

<%= @content_item.body %>

<hr>

<% unless @content_item.social_networks.blank? %>
Publish on: <%= @content_item.social_networks.map(&:description).join(',  ') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContentCalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'main_navigation' %>

    <%= yield %>
  </body>
</html>

app/views/social_networks/_form.html.erb
<%= form_with model: social_network do |form| %>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/social_networks/index.html.erb
<h1>Social Networks</h1>

<%= link_to 'Add social network', new_social_network_path %>

app/views/social_networks/new.html.erb
<h1>Add a new social network</h1>

<%= render 'form', social_network: @social_network %>